
-- insert users
-- password is 12345 (bcrypt encoded) 
insert into security_user (username, password, first_name, last_name) values 
	('admin', '$2a$04$4pqDFh9SxLAg/uSH59JCB.LwIS6QoAjM9qcE7H9e2drFuWhvTnDFi', 'Admin', 'Admin');
-- password is abcdef (bcrypt encoded)
insert into security_user (username, password, first_name, last_name) values 
	('petar', '$2a$04$Yr3QD6lbcemnrRNLbUMLBez2oEK15pdacIgfkvymQ9oMhqsEE56EK', 'Petar', 'Petrovic');

insert into security_user (username, password, first_name, last_name) values 
	('sima', '$2a$04$Yr3QD6lbcemnrRNLbUMLBez2oEK15pdacIgfkvymQ9oMhqsEE56EK', 'Sima', 'Simic');
-- password is abcdef (bcrypt encoded)
insert into security_user (username, password, first_name, last_name) values 
	('marko', '$2a$04$Yr3QD6lbcemnrRNLbUMLBez2oEK15pdacIgfkvymQ9oMhqsEE56EK', 'Marko', 'Markovic');

-- insert authorities
insert into security_authority (name) values ('ROLE_ADMIN'); -- super user
insert into security_authority (name) values ('ROLE_USER'); -- normal user

-- insert mappings between users and authorities
insert into security_user_authority (user_id, authority_id) values (1, 1); -- admin has ROLE_ADMIN
insert into security_user_authority (user_id, authority_id) values (1, 2); -- admin has ROLE_USER too
insert into security_user_authority (user_id, authority_id) values (2, 2); -- petar has ROLE_USER
insert into security_user_authority (user_id, authority_id) values (3, 2); -- sima has ROLE_USER
insert into security_user_authority (user_id, authority_id) values (4, 2); -- marko has ROLE_USER



insert into category_type(name) values ("Games"),("Technology"),("Arts"),("Food"),("Music");

-- Project

insert into project(description,image_url,money_target,name,video_url,category_id,user_id,about_project) values 
("Call of Duty: Modern Warfare is an upcoming first-person shooter video game that is being developed by Infinity Ward and published by Activision","https://upload.wikimedia.org/wikipedia/en/e/e9/CallofDutyModernWarfare%282019%29.jpg",29900,"Call Of Duty: Modern Warfare", "https://www.youtube.com/embed/bH1lHCirCGI",1,1,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu enim iaculis, malesuada erat et, condimentum justo. Nunc nec enim leo. Fusce ac placerat ipsum. Aliquam ac eros ante. Morbi ornare sed nunc eu blandit. Cras porta nisl nec diam tempus, vitae eleifend sem laoreet. Mauris venenatis nisi eget bibendum sagittis. Vivamus cursus diam ac magna rutrum interdum. Aenean eget ipsum sollicitudin, blandit augue eget, elementum nibh. Nunc augue ex, tincidunt a aliquet a, cursus eget eros. Suspendisse nisi dui, consectetur sit amet nisi ut, porta vulputate diam.
Nulla vitae turpis at nisl placerat tempus vitae quis sapien. Morbi cursus fringilla iaculis. Nunc elit ex, mattis quis massa vitae, scelerisque elementum augue. Suspendisse potenti. Donec eget nisl rhoncus, aliquet lacus id, tincidunt erat. Aliquam ligula sapien, tempus vel luctus at, sodales vitae velit. Maecenas efficitur dictum arcu in congue. Proin sed nisi fermentum, pulvinar erat ut, auctor leo. Integer ullamcorper, diam vitae iaculis lacinia, tortor urna vulputate tortor, at venenatis magna ligula finibus lectus. Sed eget tortor in augue suscipit consequat. Cras molestie massa ut eros blandit, efficitur feugiat ipsum vulputate. Duis non dapibus dolor.
Morbi a metus ut est fermentum euismod quis eget magna. Aliquam luctus finibus velit ut varius. Ut eleifend dolor sed euismod congue. Quisque eget turpis ut neque tempus pellentesque vitae ut arcu. Nulla feugiat diam ultricies, pulvinar ex non, pellentesque enim. Maecenas id nisl eu ligula vehicula faucibus. Donec non velit eros. Nullam pretium dolor lectus, ut congue eros pharetra tincidunt.
Proin convallis tristique libero, in vehicula massa scelerisque eget. Duis ut libero ac nulla consectetur lobortis in accumsan lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed tincidunt nibh a augue dapibus pulvinar. Vestibulum rutrum tortor odio, eget mollis lectus tristique at. Donec tristique nibh ultrices eleifend dignissim. Suspendisse quis lectus eu augue vehicula porttitor eget ac mi. Nam vitae nisi sapien. Nulla nec eleifend nunc. Aliquam ac felis at magna suscipit placerat. Cras interdum turpis eget quam vestibulum ultricies. Maecenas et est ut neque congue tristique. Sed gravida dolor nec convallis egestas. Cras commodo mollis nisi quis tincidunt."),
("Far Cry New Dawn is an action-adventure first-person shooter developed by Ubisoft Montreal and published by Ubisoft. The game is a spin-off of the Far Cry series and a narrative sequel to Far Cry 5.","https://en.wikipedia.org/wiki/Far_Cry_New_Dawn#/media/File:FC_New_Dawn_cover_art.jpg",388888, "Far Cry: New Dawn","https://www.youtube.com/embed/6eLHk2Eug78&has_verified=1",1,3,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu enim iaculis, malesuada erat et, condimentum justo. Nunc nec enim leo. Fusce ac placerat ipsum. Aliquam ac eros ante. Morbi ornare sed nunc eu blandit. Cras porta nisl nec diam tempus, vitae eleifend sem laoreet. Mauris venenatis nisi eget bibendum sagittis. Vivamus cursus diam ac magna rutrum interdum. Aenean eget ipsum sollicitudin, blandit augue eget, elementum nibh. Nunc augue ex, tincidunt a aliquet a, cursus eget eros. Suspendisse nisi dui, consectetur sit amet nisi ut, porta vulputate diam.

Nulla vitae turpis at nisl placerat tempus vitae quis sapien. Morbi cursus fringilla iaculis. Nunc elit ex, mattis quis massa vitae, scelerisque elementum augue. Suspendisse potenti. Donec eget nisl rhoncus, aliquet lacus id, tincidunt erat. Aliquam ligula sapien, tempus vel luctus at, sodales vitae velit. Maecenas efficitur dictum arcu in congue. Proin sed nisi fermentum, pulvinar erat ut, auctor leo. Integer ullamcorper, diam vitae iaculis lacinia, tortor urna vulputate tortor, at venenatis magna ligula finibus lectus. Sed eget tortor in augue suscipit consequat. Cras molestie massa ut eros blandit, efficitur feugiat ipsum vulputate. Duis non dapibus dolor.

Morbi a metus ut est fermentum euismod quis eget magna. Aliquam luctus finibus velit ut varius. Ut eleifend dolor sed euismod congue. Quisque eget turpis ut neque tempus pellentesque vitae ut arcu. Nulla feugiat diam ultricies, pulvinar ex non, pellentesque enim. Maecenas id nisl eu ligula vehicula faucibus. Donec non velit eros. Nullam pretium dolor lectus, ut congue eros pharetra tincidunt.

Proin convallis tristique libero, in vehicula massa scelerisque eget. Duis ut libero ac nulla consectetur lobortis in accumsan lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed tincidunt nibh a augue dapibus pulvinar. Vestibulum rutrum tortor odio, eget mollis lectus tristique at. Donec tristique nibh ultrices eleifend dignissim. Suspendisse quis lectus eu augue vehicula porttitor eget ac mi. Nam vitae nisi sapien. Nulla nec eleifend nunc. Aliquam ac felis at magna suscipit placerat. Cras interdum turpis eget quam vestibulum ultricies. Maecenas et est ut neque congue tristique. Sed gravida dolor nec convallis egestas. Cras commodo mollis nisi quis tincidunt."),
("Cyberpunk 2020, it is set fifty-seven years later in dystopian Night City, California, an open world with six distinct regions. ","https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg",149999, "Cyberpunk 2077","https://www.youtube.com/embed/YApuEWtG30w", 1, 4 , "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu enim iaculis, malesuada erat et, condimentum justo. Nunc nec enim leo. Fusce ac placerat ipsum. Aliquam ac eros ante. Morbi ornare sed nunc eu blandit. Cras porta nisl nec diam tempus, vitae eleifend sem laoreet. Mauris venenatis nisi eget bibendum sagittis. Vivamus cursus diam ac magna rutrum interdum. Aenean eget ipsum sollicitudin, blandit augue eget, elementum nibh. Nunc augue ex, tincidunt a aliquet a, cursus eget eros. Suspendisse nisi dui, consectetur sit amet nisi ut, porta vulputate diam.

Nulla vitae turpis at nisl placerat tempus vitae quis sapien. Morbi cursus fringilla iaculis. Nunc elit ex, mattis quis massa vitae, scelerisque elementum augue. Suspendisse potenti. Donec eget nisl rhoncus, aliquet lacus id, tincidunt erat. Aliquam ligula sapien, tempus vel luctus at, sodales vitae velit. Maecenas efficitur dictum arcu in congue. Proin sed nisi fermentum, pulvinar erat ut, auctor leo. Integer ullamcorper, diam vitae iaculis lacinia, tortor urna vulputate tortor, at venenatis magna ligula finibus lectus. Sed eget tortor in augue suscipit consequat. Cras molestie massa ut eros blandit, efficitur feugiat ipsum vulputate. Duis non dapibus dolor.

Morbi a metus ut est fermentum euismod quis eget magna. Aliquam luctus finibus velit ut varius. Ut eleifend dolor sed euismod congue. Quisque eget turpis ut neque tempus pellentesque vitae ut arcu. Nulla feugiat diam ultricies, pulvinar ex non, pellentesque enim. Maecenas id nisl eu ligula vehicula faucibus. Donec non velit eros. Nullam pretium dolor lectus, ut congue eros pharetra tincidunt.

Proin convallis tristique libero, in vehicula massa scelerisque eget. Duis ut libero ac nulla consectetur lobortis in accumsan lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed tincidunt nibh a augue dapibus pulvinar. Vestibulum rutrum tortor odio, eget mollis lectus tristique at. Donec tristique nibh ultrices eleifend dignissim. Suspendisse quis lectus eu augue vehicula porttitor eget ac mi. Nam vitae nisi sapien. Nulla nec eleifend nunc. Aliquam ac felis at magna suscipit placerat. Cras interdum turpis eget quam vestibulum ultricies. Maecenas et est ut neque congue tristique. Sed gravida dolor nec convallis egestas. Cras commodo mollis nisi quis tincidunt."),
("Played from a third-person perspective, the game is a cover-based third-person shooter with up to four players being able to complete missions together", "https://upload.wikimedia.org/wikipedia/en/a/af/The_Division_2_art.jpg",100000,"Tom Clancy's The Division 2","https://www.youtube.com/embed/U06clM6yJHE",1,3,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu enim iaculis, malesuada erat et, condimentum justo. Nunc nec enim leo. Fusce ac placerat ipsum. Aliquam ac eros ante. Morbi ornare sed nunc eu blandit. Cras porta nisl nec diam tempus, vitae eleifend sem laoreet. Mauris venenatis nisi eget bibendum sagittis. Vivamus cursus diam ac magna rutrum interdum. Aenean eget ipsum sollicitudin, blandit augue eget, elementum nibh. Nunc augue ex, tincidunt a aliquet a, cursus eget eros. Suspendisse nisi dui, consectetur sit amet nisi ut, porta vulputate diam.

Nulla vitae turpis at nisl placerat tempus vitae quis sapien. Morbi cursus fringilla iaculis. Nunc elit ex, mattis quis massa vitae, scelerisque elementum augue. Suspendisse potenti. Donec eget nisl rhoncus, aliquet lacus id, tincidunt erat. Aliquam ligula sapien, tempus vel luctus at, sodales vitae velit. Maecenas efficitur dictum arcu in congue. Proin sed nisi fermentum, pulvinar erat ut, auctor leo. Integer ullamcorper, diam vitae iaculis lacinia, tortor urna vulputate tortor, at venenatis magna ligula finibus lectus. Sed eget tortor in augue suscipit consequat. Cras molestie massa ut eros blandit, efficitur feugiat ipsum vulputate. Duis non dapibus dolor.

Morbi a metus ut est fermentum euismod quis eget magna. Aliquam luctus finibus velit ut varius. Ut eleifend dolor sed euismod congue. Quisque eget turpis ut neque tempus pellentesque vitae ut arcu. Nulla feugiat diam ultricies, pulvinar ex non, pellentesque enim. Maecenas id nisl eu ligula vehicula faucibus. Donec non velit eros. Nullam pretium dolor lectus, ut congue eros pharetra tincidunt.

Proin convallis tristique libero, in vehicula massa scelerisque eget. Duis ut libero ac nulla consectetur lobortis in accumsan lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed tincidunt nibh a augue dapibus pulvinar. Vestibulum rutrum tortor odio, eget mollis lectus tristique at. Donec tristique nibh ultrices eleifend dignissim. Suspendisse quis lectus eu augue vehicula porttitor eget ac mi. Nam vitae nisi sapien. Nulla nec eleifend nunc. Aliquam ac felis at magna suscipit placerat. Cras interdum turpis eget quam vestibulum ultricies. Maecenas et est ut neque congue tristique. Sed gravida dolor nec convallis egestas. Cras commodo mollis nisi quis tincidunt."),
("The RoboMaster S1 is a game-changing educational robot built to unlock the potential in every learner.","https://ph-files.imgix.net/97085dbc-5d9f-4374-bcbf-e1e11454b9b5?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=300.3&h=221&fit=max",98888,"RoboMaster S1", "https://www.youtube.com/embed/6GpdoJXpo2U&t=2s",2,2,"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu enim iaculis, malesuada erat et, condimentum justo. Nunc nec enim leo. Fusce ac placerat ipsum. Aliquam ac eros ante. Morbi ornare sed nunc eu blandit. Cras porta nisl nec diam tempus, vitae eleifend sem laoreet. Mauris venenatis nisi eget bibendum sagittis. Vivamus cursus diam ac magna rutrum interdum. Aenean eget ipsum sollicitudin, blandit augue eget, elementum nibh. Nunc augue ex, tincidunt a aliquet a, cursus eget eros. Suspendisse nisi dui, consectetur sit amet nisi ut, porta vulputate diam.

Nulla vitae turpis at nisl placerat tempus vitae quis sapien. Morbi cursus fringilla iaculis. Nunc elit ex, mattis quis massa vitae, scelerisque elementum augue. Suspendisse potenti. Donec eget nisl rhoncus, aliquet lacus id, tincidunt erat. Aliquam ligula sapien, tempus vel luctus at, sodales vitae velit. Maecenas efficitur dictum arcu in congue. Proin sed nisi fermentum, pulvinar erat ut, auctor leo. Integer ullamcorper, diam vitae iaculis lacinia, tortor urna vulputate tortor, at venenatis magna ligula finibus lectus. Sed eget tortor in augue suscipit consequat. Cras molestie massa ut eros blandit, efficitur feugiat ipsum vulputate. Duis non dapibus dolor.

Morbi a metus ut est fermentum euismod quis eget magna. Aliquam luctus finibus velit ut varius. Ut eleifend dolor sed euismod congue. Quisque eget turpis ut neque tempus pellentesque vitae ut arcu. Nulla feugiat diam ultricies, pulvinar ex non, pellentesque enim. Maecenas id nisl eu ligula vehicula faucibus. Donec non velit eros. Nullam pretium dolor lectus, ut congue eros pharetra tincidunt.

Proin convallis tristique libero, in vehicula massa scelerisque eget. Duis ut libero ac nulla consectetur lobortis in accumsan lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed tincidunt nibh a augue dapibus pulvinar. Vestibulum rutrum tortor odio, eget mollis lectus tristique at. Donec tristique nibh ultrices eleifend dignissim. Suspendisse quis lectus eu augue vehicula porttitor eget ac mi. Nam vitae nisi sapien. Nulla nec eleifend nunc. Aliquam ac felis at magna suscipit placerat. Cras interdum turpis eget quam vestibulum ultricies. Maecenas et est ut neque congue tristique. Sed gravida dolor nec convallis egestas. Cras commodo mollis nisi quis tincidunt."),
("With the Jabra Elite 65t In-Ear Passive Noise Cancelling Truly Wireless Bluetooth Headphones, you don't have to be tied down to your mobile device.","https://multimedia.bbycastatic.ca/multimedia/products/500x500/123/12321/12321947.jpg",8000,"Jabra","https://www.youtube.com/embed/p8c-RB7RimM",2,4, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu enim iaculis, malesuada erat et, condimentum justo. Nunc nec enim leo. Fusce ac placerat ipsum. Aliquam ac eros ante. Morbi ornare sed nunc eu blandit. Cras porta nisl nec diam tempus, vitae eleifend sem laoreet. Mauris venenatis nisi eget bibendum sagittis. Vivamus cursus diam ac magna rutrum interdum. Aenean eget ipsum sollicitudin, blandit augue eget, elementum nibh. Nunc augue ex, tincidunt a aliquet a, cursus eget eros. Suspendisse nisi dui, consectetur sit amet nisi ut, porta vulputate diam.

Nulla vitae turpis at nisl placerat tempus vitae quis sapien. Morbi cursus fringilla iaculis. Nunc elit ex, mattis quis massa vitae, scelerisque elementum augue. Suspendisse potenti. Donec eget nisl rhoncus, aliquet lacus id, tincidunt erat. Aliquam ligula sapien, tempus vel luctus at, sodales vitae velit. Maecenas efficitur dictum arcu in congue. Proin sed nisi fermentum, pulvinar erat ut, auctor leo. Integer ullamcorper, diam vitae iaculis lacinia, tortor urna vulputate tortor, at venenatis magna ligula finibus lectus. Sed eget tortor in augue suscipit consequat. Cras molestie massa ut eros blandit, efficitur feugiat ipsum vulputate. Duis non dapibus dolor.

Morbi a metus ut est fermentum euismod quis eget magna. Aliquam luctus finibus velit ut varius. Ut eleifend dolor sed euismod congue. Quisque eget turpis ut neque tempus pellentesque vitae ut arcu. Nulla feugiat diam ultricies, pulvinar ex non, pellentesque enim. Maecenas id nisl eu ligula vehicula faucibus. Donec non velit eros. Nullam pretium dolor lectus, ut congue eros pharetra tincidunt.

Proin convallis tristique libero, in vehicula massa scelerisque eget. Duis ut libero ac nulla consectetur lobortis in accumsan lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed tincidunt nibh a augue dapibus pulvinar. Vestibulum rutrum tortor odio, eget mollis lectus tristique at. Donec tristique nibh ultrices eleifend dignissim. Suspendisse quis lectus eu augue vehicula porttitor eget ac mi. Nam vitae nisi sapien. Nulla nec eleifend nunc. Aliquam ac felis at magna suscipit placerat. Cras interdum turpis eget quam vestibulum ultricies. Maecenas et est ut neque congue tristique. Sed gravida dolor nec convallis egestas. Cras commodo mollis nisi quis tincidunt.");


insert into faq(answer,question,project_id) values ("Lorem ipsum dolor sit amet, consectetur adipiscing elit ?","Nullam ac mattis orci. In hendrerit nibh risus, sit amet.",1),
("Aliquam eu nisl sit amet lacus lobortis luctus ?",	"Nullam ac mattis orci",1),("Curabitur euismod sed purus id blandit. Suspendisse ut sodales risus ?", "Donec magna sem, malesuada sed pharetra eu, ullamcorper non nulla.",1);

insert into donation(donation,project_id,user_id) values (4009,1,1),(200,1,2),(5099,1,3),(409,1,4);

insert into commentar(commentar,project_id,user_id) values(" Nunc augue ex, tincidunt a aliquet a, cursus eget eros.",1,1),("Morbi cursus fringilla iaculis",1,2),("Quisque eget turpis ut neque tempus pellentesque vitae ut arcu.",1,2),
(" Nunc augue ex, tincidunt a aliquet a, cursus eget eros.",2,1),(" Nunc augue ex, tincidunt a aliquet a, cursus eget eros.",2,3),(" Nunc augue ex, tincidunt a aliquet a, cursus eget eros.",2,4),(" Nunc augue ex, tincidunt a aliquet a, cursus eget eros.",3,1)
,(" Nunc augue ex, tincidunt a aliquet a, cursus eget eros.",3,2),(" Nunc augue ex, tincidunt a aliquet a, cursus eget eros.",4,1),(" Nunc augue ex, tincidunt a aliquet a, cursus eget eros.",5,3),("Quisque eget turpis ut neque tempus pellentesque vitae ut arcu.",3,2),
("Quisque eget turpis ut neque tempus pellentesque vitae ut arcu.",4,3),("Quisque eget turpis ut neque tempus pellentesque vitae ut arcu.",5,1)